/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 light_bulb.glb -T 
Files: light_bulb.glb [1.42MB] > /Users/mattwilliams/Desktop/portfolioWebsite/myWebsite/public/models/light_bulb-transformed.glb [193.86KB] (86%)
Author: JacquelineM (https://sketchfab.com/JacquelineM)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/light-bulb-b05d65aada034ccebdc73d5982108ea2
Title: Light Bulb
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function LightBulb(props) {
  const { nodes, materials } = useGLTF('/models/light_bulb-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials.Material} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_3.geometry} material={materials.transparente_del_foco} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/models/light_bulb-transformed.glb')
